### ISSUE TITLE
Spiele nach auswählbar/werden nicht angezeigt auf dem Frontend

### ISSUE THREAD

**Issue by Draakoor** [kveldscholten/gamelist#11]
Fatal error: Uncaught Error: Class 'Modules\Gamelist\Mappers\Entrants' not found in /var/customers/webs/ni87616_5/reapercrew/application/modules/gamelist/controllers/Index.php:24 Stack trace: #0 /var/customers/webs/ni87616_5/reapercrew/application/libraries/Ilch/Page.php(237): Modules\Gamelist\Controllers\Index->indexAction() #1 /var/customers/webs/ni87616_5/reapercrew/application/libraries/Ilch/Page.php(130): Ilch\Page->loadController() #2 /var/customers/webs/ni87616_5/reapercrew/index.php(63): Ilch\Page->loadPage() #3 {main} thrown in /var/customers/webs/ni87616_5/reapercrew/application/modules/gamelist/controllers/Index.php on line 24

**Comment by kveldscholten** [comment]
Ich hab es gerade mit einer frisch Installation getestet und kann keinen Fehler erkennen
